POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXItMiIsImlkIjoiNWM2ZDVjNjMzMmZjZTMxZjg4YzA4ZDNjIiwiaWF0IjoxNTUwNjcxMjM3fQ.dWMbJJib-X7C0WRkj2C1NVdUpnEAXrKozvlP2wYRcz8

{
  "title": "blog 1",
  "author": "Author 1",
  "url": "www.blog-2.com",
  "likes": 22,
  "userId":"5c6d5a498d52670a7831fd65"
}
